### PR TITLE
PRIPAD-5118 Read release notes text file instead of html

### PR DESCRIPTION
**Pull request by remover**

### CODE REVIEW

**Comment by steveanthony** [comment]
Looks good to me.

**Comment by sebskuse** [comment]
Just a thought... If we've got both an apk and an ipa in the directory, should we have different release notes for each?

**Comment by sebskuse** [comment]
Doesn't look like it from the acceptance criteria.

**Comment by dhardiman** [comment]
Yeah, I'm assuming that apk and ipa would be delivered in different directories to be honest.

**Pull request merged**
